name: webside_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

platforms:
  web:

dependencies:
  flutter:
    sdk: flutter
  stream_chat_flutter: ^5.1.0
  unique_name_generator: ^1.0.0
  crypto: ^3.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


assets:
  - .env